first_app/urls.py
from first_app import views
from django.urls import re_path, path

urlpatterns = [
  re_path(r'^$', views.index, name="index"),
  # path('brian/', views.brian, name="brian"),
  # path('table/', views.table, name="table"),
  # path('users/', views.users, name="users"),
  # path('form/', views.form, name="form"),
  # path('signup/', views.signup, name="signup")
  path('register/', views.register, name="register"),
  path('logout/', views.user_logout, name="logout"),
  path('login/', views.user_login, name="user_login")
]

# * necessary if using relative URL
app_name = "first_app"

sample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  portfolio_site = models.URLField(blank="True")
  profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

  def __str__(self):
      return self.user.username


# Create your models here.
# class User(models.Model):
#   first_name = models.CharField(max_length=50);
#   last_name = models.CharField(max_length=50);
#   email = models.EmailField(max_length=128, unique=True);

#   def __str__(self):
#     return "{}, {} ({})".format(self.last_name, self.first_name, self.email)

class Topic(models.Model):
  top_name = models.CharField(max_length=264, unique=True)

  def __str__(self):
    return self.top_name

class Webpage(models.Model):
  topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
  name = models.CharField(max_length=264, unique=True)
  url = models.URLField(unique=True)

  def __str__(self):
    return self.url

class AccessRecord(models.Model):
  name = models.ForeignKey(Webpage, on_delete=models.DO_NOTHING)
  date = models.DateField()

  def __str__(self):
    return str(self.date)

first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import User, UserProfileInfo

class UserForm(forms.ModelForm):
  password = forms.CharField(widget=forms.PasswordInput())

  class Meta():
    model = User
    fields = ('username', 'email','password')

class UserProfileInfoForm(forms.ModelForm):
  class Meta():
    model = UserProfileInfo
    fields = ('portfolio_site', 'profile_pic')

def start_with_z(value):
  if value[0] != 'z':
    raise forms.ValidationError('error msg')

class SignUp(forms.ModelForm):
  class Meta():
    model = User
    fields = "__all__"

class FormName(forms.Form):
  name = forms.CharField(validators=[start_with_z])
  email = forms.EmailField()
  confirm_email = forms.EmailField()
  text = forms.CharField(widget=forms.Textarea)
  # botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
  #                              validators=[validators.MaxLengthValidator(0)])

  # def clean_botcatcher(self):
  #   botcatcher = self.cleaned_data['botcatcher']
  #   if len(botcatcher) > 0:
  #       raise forms.ValidationError("FOUND U A BOT")
  #   return botcatcher

  def clean(self):
    all_clean_data = super().clean()
    if all_clean_data['email'] != all_clean_data['confirm_email']:
      raise forms.ValidationError("Emails must match")

first_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from first_app.models import Topic, Webpage, AccessRecord #User
from . import forms
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
  # my_dict = {'insert_me': "Hello I am from views.py"}
  context_dict = {"text": 'hello my Name iS bRiaN', "num": 500}
  return render(request, 'first_app/index.html', context_dict)
  # return HttpResponse("<em>Helo Brian!</em>")

@login_required #only accessible if logged in
def user_logout(request):
  logout(request)
  return HttpResponseRedirect(reverse('first_app:index'))

def user_login(request):
  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')
    print(username, password)
    user = authenticate(username=username, password=password)

    if user:
      if user.is_active:
        login(request, user)
        return HttpResponseRedirect(reverse('first_app:index'))
      else:
        return HttpResponse("Account not active")
    else:
      print('Someone failed to login')
      return HttpResponse('invalid credentials')
  else:
    return render(request, 'first_app/login.html', {})

def register(request):
  registered = False
  if request.method == "POST":
    user_form = forms.UserForm(data=request.POST)
    profile_form = forms.UserProfileInfoForm(data=request.POST)
    if user_form.is_valid() and profile_form.is_valid():
      user = user_form.save()
      user.set_password(user.password)
      user.save()

      profile = profile_form.save(commit=False)
      profile.user = user

      if 'profile_pic' in request.FILES:
        profile.profile_pic = request.FILES['profile_pic']

      profile.save()

      registered = True
    else:
      print(user_form.errors, profile_form.errors)
  else:
    user_form = forms.UserForm()
    profile_form = forms.UserProfileInfoForm()

  return render(request, 'first_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def brian(request):
  return HttpResponse("<strong>I miss you</strong>")

def signup(request):
  form = forms.SignUp()
  if request.method == "POST":
    form = forms.SignUp(request.POST)
    if form.is_valid():
      form.save(commit=True)
      return users(request)
  return render(request, 'first_app/form.html', context={'form':form})


def table(request):
  webpages_list = AccessRecord.objects.order_by('date')
  date_dict = {'access_records' : webpages_list }
  return render(request, 'first_app/table.html', context=date_dict)

def form(request):
  form = forms.FormName();
  if request.method == "POST":
    form = forms.FormName(request.POST)
    if form.is_valid():
      print("validation success")
      print(form.cleaned_data['name'])
      print(form.cleaned_data['email'])
      print(form.cleaned_data['text'])

  return render(request, 'first_app/form.html', {'form':form})

# def users(request):
#   users_list = User.objects.order_by('last_name')
#   user_dict = {'users': users_list}
#   return render(request, 'first_app/users.html', context=user_dict)

templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <title>First Django App</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">My First Django App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'first_app:index'%}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:form'%}">Form</a>
        </li> {% endcomment %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% comment %} <a class="dropdown-item" href="{% url 'first_app:users'%}">Users</a>
            <a class="dropdown-item" href="{% url 'first_app:table'%}">Table</a> {% endcomment %}
            <a class="dropdown-item" href="{% url 'first_app:register'%}">Register</a>
            {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'first_app:logout'%}">Logout</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'first_app:user_login'%}">Login</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'admin:index'%}">Admin</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  {% block body_block %}
  {% endblock %}
</body>
</html>

templates/first_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Form</title>
</head>
<body>
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit" />
  </form>
  {% comment %} using relative url {% endcomment %}
  <a href="{% url 'first_app:users' %}">View All Users</a>
  <a href="{% url 'admin:index' %}">Admin Portal</a>
  <a href="{% url 'first_app:index' %}">Home</a>
  {% comment %} <a href="{% url 'index' %}">Home</a> {% endcomment %}
</body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% load staticfiles %}
  {% block body_block %}
    <h1>Welcome to DJANGO</h1>
    {% comment %} {{insert_me}} {% endcomment %}
    <img src='{% static "images/MS.png" %}' alt="">
      {% block other_block %}
      {% endblock %}

    {% comment %} template filter {% endcomment %}
      {{ text|cut:'e' }}
      {{ num|add:-56 }}
  {% endblock %}

templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block%}

    <h1>Login</h1>
    <h3>Fill out the form: </h3>
    <form method="POST" action="{% url 'first_app:user_login' %}">
      {% csrf_token %}
      <input type="text" placeholder="username" name="username">
      <input type="password" placeholder="password" name="password">
      <input type="submit" value="Login">
    </form>
{% endblock %}

templates/first_app/registration.html
{% extends 'first_app/base.html' %}
{% load staticfiles %}

{% block body_block%}

  {% if registered %}

    <h1>Thank you for registering!</h1>

  {% else %}
    <h1>Reigster here</h1>
    <h3>Fill out the form: </h3>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" value="Register">
    </form>
  {% endif %}
{% endblock %}

templates/first_app/table.html
<!DOCTYPE html>
{% extends 'first_app/index.html' %}
{% load staticfiles %}
{% block other_block %}
  <h1>Table</h1>
  {% if access_records %}
  <table>
    <thead>
      <th>Site Name</th>
      <th>Date Accessed</th>
    </thead>
    {% for acc in access_records %}
    <tr>
      <td>{{ acc.name }}</td>
      <td>{{ acc.date }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptates rem minus nisi, provident nesciunt fugit obcaecati delectus repellat magni labore eius ipsum accusantium molestias. Dolorem sint unde nemo voluptas assumenda.</p>
  {% endif %}
{% endblock %}

templates/first_app/users.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <title>Users</title>
</head>
<body>
  <h1>Users</h1>
  <ol>
    {% for u in users %}
    <li>
      User Info
      <ul>
        <li>First Name: {{u.first_name}}</li>
        <li>Last Name: {{u.last_name}}</li>
        <li>Email: {{u.email}}</li>
      </ul>
    </li>
    {% endfor %}
  </ol>
</body>
</html>